CREATE TABLE DEPARTAMENTO(
ID_DEPARTAMENTO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
NOMBRE TEXT NOT NULL 
);

CREATE TABLE HORARIO(
ID_HORARIO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
HORA INTEGER NOT NULL 
);


CREATE TABLE TRABAJADOR (
RUT_TRABAJADOR TEXT PRIMARY KEY NOT NULL ,
NOMBRE_TRABAJADOR TEXT NOT NULL,
APELLIDO_TRABAJADOR TEXT NOT NULL,
FECHA_NACIMIENTO TEXT NOT NULL,
GENERO TEXT NOT NULL,
ID_DEPARTAMENTO INTEGER NOT NULL,
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);

CREATE TABLE TRABAJADOR_HORARIO(
ID_TURNO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
RUT_TRABAJADOR TEXT NOT NULL,
ID_HORARIO INTEGER NOT NULL,
FOREIGN KEY (RUT_TRABAJADOR) REFERENCES TRABAJADOR(RUT_TRABAJADOR),
FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO)
);

PRAGMA foreign_keys = ON;


cursor.execute('''INSERT INTO DEPARTAMENTO VALUES (null,'Informatica');''')
cursor.execute('''INSERT INTO DEPARTAMENTO VALUES (null,'Finanzas');''')
cursor.execute('''INSERT INTO DEPARTAMENTO VALUES (null,'Ventas');''')
cursor.execute('''INSERT INTO DEPARTAMENTO VALUES (null,'Compras');''')
cursor.execute('''INSERT INTO DEPARTAMENTO VALUES (null,'Marketing');''')


cursor.execute('''INSERT INTO HORARIO VALUES (null,'09:00');''')
cursor.execute('''INSERT INTO HORARIO VALUES (null,'10:00');''')
cursor.execute('''INSERT INTO HORARIO VALUES (null,'11:00');''')
cursor.execute('''INSERT INTO HORARIO VALUES (null,'12:00');''')
cursor.execute('''INSERT INTO HORARIO VALUES (null,'13:00');''')
cursor.execute('''INSERT INTO HORARIO VALUES (null,'14:00');''')
cursor.execute('''INSERT INTO HORARIO VALUES (null,'15:00');''')
cursor.execute('''INSERT INTO HORARIO VALUES (null,'16:00');''')
cursor.execute('''INSERT INTO HORARIO VALUES (null,'17:00');''')
cursor.execute('''INSERT INTO HORARIO VALUES (null,'18:00');''')
cursor.execute('''INSERT INTO HORARIO VALUES (null,'19:00');''')


cursor.execute('''INSERT INTO TRABAJADOR VALUES ('11111111-1','Juan','Perez','1985-02-01','Masculino',1);''')
cursor.execute('''INSERT INTO TRABAJADOR VALUES ('22222222-2','Pedro','Perez','1995-01-23','Masculino',2);''')
cursor.execute('''INSERT  INTO TRABAJADOR VALUES ('33333333-3','Carla','Montenegro','1990-10-15','Femenino',3);''')


cursor.execute('''INSERT INTO TRABAJADOR_HORARIO VALUES (null,'11111111-1',1);''')
cursor.execute('''INSERT INTO TRABAJADOR_HORARIO VALUES (null,'11111111-1',2);''')
cursor.execute('''INSERT INTO TRABAJADOR_HORARIO VALUES (null,'33333333-3',3);''')
cursor.execute('''INSERT INTO TRABAJADOR_HORARIO VALUES (null,'33333333-3',4);''')
cursor.execute('''INSERT INTO TRABAJADOR_HORARIO VALUES (null,'33333333-3',5);''')

select *FROM TRABAJADOR
SELECT *FROM TRABAJADOR_HORARIO
SELECT *FROM DEPARTAMENTO


SELECT count() as cantidad, genero as numero  FROM TRABAJADOR group by GENERO
SELECT RUT_TRABAJADOR AS RUT, NOMBRE_TRABAJADOR AS NOMBRE, TRABAJADOR.APELLIDO_TRABAJADOR AS APELLIDO, TRABAJADOR.GENERO AS GENERO, DEPARTAMENTO.NOMBRE AS DEPARTAMENTO FROM TRABAJADOR JOIN DEPARTAMENTO ON TRABAJADOR.ID_DEPARTAMENTO=DEPARTAMENTO.ID_DEPARTAMENTO WHERE TRABAJADOR.GENERO='Masculino'
SELECT RUT_TRABAJADOR AS RUT, NOMBRE_TRABAJADOR AS NOMBRE, TRABAJADOR.APELLIDO_TRABAJADOR AS APELLIDO, TRABAJADOR.GENERO AS GENERO, DEPARTAMENTO.NOMBRE AS DEPARTAMENTO FROM TRABAJADOR JOIN DEPARTAMENTO ON TRABAJADOR.ID_DEPARTAMENTO=DEPARTAMENTO.ID_DEPARTAMENTO WHERE TRABAJADOR.GENERO='Femenino'

SELECT TRABAJADOR.RUT_TRABAJADOR AS RUT, TRABAJADOR.NOMBRE_TRABAJADOR AS NOMBRE, TRABAJADOR.APELLIDO_TRABAJADOR AS , TRABAJADOR.FECHA_NACIMIENTO AS FECHA DE NACIMIENTO FROM TRABAJADOR JOIN DEPARTAMENTO ON TRABAJADOR.ID_DEPARTAMENTO=DEPARTAMENTO.ID_DEPARTAMENTO





SELECT *from TRABAJADOR where GENERO='Femenino'
select TRABAJADOR.NOMBRE_TRABAJADOR AS NOMBRE, HORARIO.HORA AS HORA from TRABAJADOR_HORARIO JOIN TRABAJADOR ON TRABAJADOR_HORARIO.RUT_TRABAJADOR=TRABAJADOR.RUT_TRABAJADOR JOIN HORARIO ON TRABAJADOR_HORARIO.ID_HORARIO=HORARIO.ID_HORARIO WHERE TRABAJADOR.RUT_TRABAJADOR='33333333-3'



















