CREATE TABLE DEPARTAMENTO(
ID_DEPARTAMENTO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
NOMBRE TEXT NOT NULL 
);

CREATE TABLE HORARIO(
ID_HORARIO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
HORA INTEGER NOT NULL 
);


CREATE TABLE TRABAJADOR (
RUT_TRABAJADOR TEXT PRIMARY KEY NOT NULL ,
NOMBRE_TRABAJADOR TEXT NOT NULL,
APELLIDO_TRABAJADOR TEXT NOT NULL,
FECHA_NACIMIENTO TEXT NOT NULL,
GENERO TEXT NOT NULL,
ID_DEPARTAMENTO INTEGER NOT NULL,
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);

CREATE TABLE TRABAJADOR_HORARIO(
ID_TURNO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
RUT_TRABAJADOR TEXT NOT NULL,
ID_HORARIO INTEGER NOT NULL,
FOREIGN KEY (RUT_TRABAJADOR) REFERENCES TRABAJADOR(RUT_TRABAJADOR),
FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO)
);

PRAGMA foreign_keys = ON;
